### ISSUE TITLE
expose list_branches

### ISSUE THREAD

**Issue by wiso** [chrisburr/root_pandas#25]
Usually when opening a ROOT file I don't know the names of the branches, so it would be good to expose a way to list the names of the branches, without importing other modules. Same for the name of the trees.

**Comment by wiso** [comment]
See pull request #26

**Comment by ibab** [comment]
I'd prefer to not re-export functions from `root_numpy` as part of the `root_pandas` API.
Also, this functionality can be implemented in a pandas-compatible way as part of #3.

**Comment by chrisburr** [comment]
Closing for the reason stated by @ibab, until #3 is resolved I suggest this is used instead:

```python
from root_numpy import list_branches, list_trees
```
