### ISSUE TITLE
Tag a new version

### ISSUE THREAD

**Issue by alexpearce** [chrisburr/root_pandas#33]
Is it time for root_pandas 0.1.2? I keep finding myself doing

``` shell
$ pip install --user git+git://github.com/ibab/root_pandas@2001dcc8675d19fce8b15f02f63aa47944eec3d6
```

to pick up the [latest fix](https://github.com/ibab/root_pandas/commit/2001dcc8675d19fce8b15f02f63aa47944eec3d6).

**Comment by alexpearce** [comment]
Maybe this should wait until 22nd Feburary, then it'd be a year in between versions. Anniversary update! 😉

**Comment by mayou36** [comment]
So, to my understanding, the 22nd February already passed ;)
What's about a new release? I think this would really be more convenient for most of the people.

**Comment by ttekampe** [comment]
*push* maybe its going to be a christmas gift

**Comment by chrisburr** [comment]
[Christmas has come early!](https://github.com/chrisburr/root_pandas/releases/tag/v0.2.0) 🎉
